linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - maligned
    - scopelint

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

output:
  sort-results: true