linters:
  enable-all: true
  disable:
    - gochecknoglobals # usually just false positives
    - paralleltest # unreliable with integration tests
    - exhaustruct # too many exceptions
    - exhaustivestruct # too many exceptions
    - tagliatelle # restricts json/yaml formatting, not applicable in this app
    - goconst # finds repeated strings >= 3 times; but usually that's OK
    - goerr113 # all false positives
    - varnamelen

    # The following are deprecated
    - maligned
    - scopelint
    - golint
    - interfacer
    - ifshort
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true # enable "default"-case in switch as catch-all for all other options

issues:
  max-per-linter: 0 # default is 50, 0 = disable
  max-same-issues: 0 # default is 3, 0 = disable

output:
  sort-results: true