version: "3.7"

# these are all services needed for the integration tests
services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=goboot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=secret
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/var/lib/elasticsearch/data
    ports:
      - 9200:9200

  pubsub:
    image: knarz/pubsub-emulator
    ports:
      - "8085:8085"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: >
      --requirepass secret

volumes:
  pgdata:
  esdata:
