package context

import (
	"github.com/nielskrijger/go-utils/test"
	"github.com/rs/zerolog"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// AppService is an autogenerated mock type for the AppService type
type appServiceMock struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *appServiceMock) Close() {
	_m.Called()
}

// Configure provides a mock function with given fields: ctx
func (_m *appServiceMock) Configure(ctx *AppContext) {
	_m.Called(ctx)
}

// Init provides a mock function with given fields:
func (_m *appServiceMock) Init() {
	_m.Called()
}

func TestAppContext_Logger(t *testing.T) {
	ctx := NewAppContext("../test/conf", "test")
	testLogger := &test.TestLogger{}
	ctx.Log = zerolog.New(testLogger)

	ctx.Configure()

	entries := testLogger.Lines()
	assert.Len(t, entries, 2)
	assert.Equal(t, "starting app services configuration", entries[0]["message"])
	assert.Equal(t, "info", entries[1]["level"])
	assert.Equal(t, "finished app services configuration", entries[1]["message"])
	assert.Equal(t, "info", entries[1]["level"])
}

func TestAppContext_Configure(t *testing.T) {
	serviceMock1 := &appServiceMock{}
	serviceMock2 := &appServiceMock{}
	ctx := NewAppContext("../test/conf", "postgres")
	serviceMock1.On("Configure", ctx).Return()
	serviceMock2.On("Configure", ctx).Return()
	ctx.AddService(serviceMock1)
	ctx.AddService(serviceMock2)

	ctx.Configure()

	serviceMock1.AssertExpectations(t)
	serviceMock2.AssertExpectations(t)
}

func TestAppContext_Init(t *testing.T) {
	serviceMock1 := &appServiceMock{}
	serviceMock2 := &appServiceMock{}
	ctx := NewAppContext("../test/conf", "postgres")
	serviceMock1.On("Init").Return()
	serviceMock2.On("Init").Return()
	ctx.AddService(serviceMock1)
	ctx.AddService(serviceMock2)

	ctx.Init()

	serviceMock1.AssertExpectations(t)
	serviceMock2.AssertExpectations(t)
}

func TestAppContext_Close(t *testing.T) {
	serviceMock1 := &appServiceMock{}
	serviceMock2 := &appServiceMock{}
	ctx := NewAppContext("../test/conf", "postgres")
	serviceMock1.On("Close").Return()
	serviceMock2.On("Close").Return()
	ctx.AddService(serviceMock1)
	ctx.AddService(serviceMock2)

	ctx.Close()

	serviceMock1.AssertExpectations(t)
	serviceMock2.AssertExpectations(t)
}
