name: tests
on: push
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: test
        uses: cedrickring/golang-action@1.7.0
        with:
          args: make integration