name: Tests
on: push
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Start containers
        run: docker-compose up -d

      - name: Check container status
        run: docker ps -a

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: Run tests
        run: make integration

      - name: Stop containers
        if: always()
        run: docker-compose down