name: unit tests
on: push
jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: cedrickring/golang-action
        with:
          args: make test