name: unit tests
on: push
jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make test